/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ocr/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ocr Contract */
        post: operations["ocr_contract_api_ocr_contract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ocr/contract/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ocr Contract Structured */
        post: operations["ocr_contract_structured_api_ocr_contract_structured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest File */
        post: operations["ingest_file_rag_ingest_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Upload */
        post: operations["ingest_upload_rag_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest-sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Sample */
        post: operations["ingest_sample_rag_ingest_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_rag_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_rag_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_rag_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Types */
        get: operations["types_checklist_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/{loai_hop_dong}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_checklist__loai_hop_dong__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist/evaluate-clause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_checklist_evaluate_clause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_ingest_upload_rag_ingest_upload_post */
        Body_ingest_upload_rag_ingest_upload_post: {
            /** File */
            file: string;
        };
        /** Body_ocr_contract_api_ocr_contract_post */
        Body_ocr_contract_api_ocr_contract_post: {
            /** File */
            file: string;
        };
        /** Body_ocr_contract_structured_api_ocr_contract_structured_post */
        Body_ocr_contract_structured_api_ocr_contract_structured_post: {
            /** File */
            file: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Query */
            query: string;
            /**
             * Conversation
             * @default []
             */
            conversation: components["schemas"]["Message"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
        };
        /** ChecklistSummary */
        ChecklistSummary: {
            /** Loai Hop Dong */
            loai_hop_dong: string;
            /** Ten Hien Thi */
            ten_hien_thi: string;
            /** Phien Ban */
            phien_ban: string;
            /** Ben A */
            ben_a: string;
            /** Ben B */
            ben_b: string;
            /** Ben Duoc Bao Ve */
            ben_duoc_bao_ve: string;
            /** So Dieu Khoan */
            so_dieu_khoan: number;
            /** So Red Flags */
            so_red_flags: number;
            /** So Unfair */
            so_unfair: number;
        };
        /** CitationResponse */
        CitationResponse: {
            /** Source File */
            source_file: string;
            /** Law Title */
            law_title: string;
            /** Article */
            article: string;
            /** Clause */
            clause?: string | null;
            /** Point */
            point?: string | null;
            /** Quote */
            quote: string;
            /** Location */
            location: string;
            /** Score */
            score: number;
        };
        /** ContractClause */
        ContractClause: {
            /** Article No */
            article_no?: string | null;
            /** Title */
            title?: string | null;
            /** Items */
            items?: string[];
        };
        /** ContractEquipmentItem */
        ContractEquipmentItem: {
            /** Index */
            index?: number | null;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Condition */
            condition?: string | null;
        };
        /** ContractInfo */
        ContractInfo: {
            /** Contract Type */
            contract_type?: string | null;
            /** Contract Number */
            contract_number?: string | null;
            /** Sign Date */
            sign_date?: string | null;
            /** Term Text */
            term_text?: string | null;
            /** Rent Price */
            rent_price?: string | null;
            /** Deposit */
            deposit?: string | null;
            /** Area */
            area?: string | null;
            /** Property Address */
            property_address?: string | null;
        };
        /** ContractOCRResponse */
        ContractOCRResponse: {
            /** Success */
            success: boolean;
            /** Document Id */
            document_id: string;
            /** Source Filename */
            source_filename: string;
            /** Markdown Filename */
            markdown_filename: string;
            /** Markdown */
            markdown: string;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number | string;
            } | null;
        };
        /** ContractParty */
        ContractParty: {
            /** Role Label */
            role_label?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Id Number */
            id_number?: string | null;
            /** Id Issue Date */
            id_issue_date?: string | null;
            /** Id Issue Place */
            id_issue_place?: string | null;
            /** Phone */
            phone?: string | null;
            /** Permanent Address */
            permanent_address?: string | null;
        };
        /** ContractStructuredOCRResponse */
        ContractStructuredOCRResponse: {
            /** Success */
            success: boolean;
            /** Document Id */
            document_id: string;
            /** Source Filename */
            source_filename: string;
            /** Markdown Filename */
            markdown_filename: string;
            /** Markdown */
            markdown: string;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number | string;
            } | null;
            structured: components["schemas"]["StructuredContractResponse"];
        };
        /** DanhGia */
        DanhGia: {
            /** Phan Tich */
            phan_tich?: components["schemas"]["PhanTichItem"][];
            /**
             * Muc Rui Ro Tong
             * @default khong
             */
            muc_rui_ro_tong: string;
            /** Matched Red Flags */
            matched_red_flags?: components["schemas"]["MatchedFlag"][];
            /** Matched Unfair Clauses */
            matched_unfair_clauses?: components["schemas"]["MatchedFlag"][];
            /** Nhan Xet */
            nhan_xet?: string | null;
            /** De Xuat Sua */
            de_xuat_sua?: string | null;
        };
        /** EvaluateClauseRequest */
        EvaluateClauseRequest: {
            /** Loai Hop Dong */
            loai_hop_dong: string;
            /** Clause Text */
            clause_text: string;
        };
        /** EvaluateClauseResponse */
        EvaluateClauseResponse: {
            /** Loai Hop Dong */
            loai_hop_dong: string;
            /** Checklist Id */
            checklist_id: string;
            /** Model */
            model: string;
            /** Ben Duoc Bao Ve */
            ben_duoc_bao_ve: string;
            danh_gia: components["schemas"]["DanhGia"];
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "supported" | "insufficient_evidence" | "unsupported" | "legacy_unverified";
            /** Luu Y */
            luu_y: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexStatusResponse */
        IndexStatusResponse: {
            /** Parents */
            parents: number;
            /** Children */
            children: number;
            /** Indexed */
            indexed: boolean;
        };
        /** IngestFileRequest */
        IngestFileRequest: {
            /** Filepath */
            filepath: string;
        };
        /** IngestFileResponse */
        IngestFileResponse: {
            /** Parents */
            parents: number;
            /** Children */
            children: number;
            /**
             * Status
             * @default success
             */
            status: string;
        };
        /**
         * LegalCitation
         * @description One retrieved-and-verified legal citation (mirrors rag.citation.Citation).
         */
        LegalCitation: {
            /**
             * Source File
             * @default
             */
            source_file: string;
            /**
             * Law Title
             * @default
             */
            law_title: string;
            /**
             * Article
             * @default
             */
            article: string;
            /** Clause */
            clause?: string | null;
            /** Point */
            point?: string | null;
            /**
             * Quote
             * @default
             */
            quote: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Selection Confidence */
            selection_confidence?: ("high" | "medium" | "low") | null;
        };
        /** MatchedFlag */
        MatchedFlag: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Muc Rui Ro
             * @default
             */
            muc_rui_ro: string;
            /**
             * Trich Dan
             * @default
             */
            trich_dan: string;
            /**
             * Ly Do
             * @default
             */
            ly_do: string;
            /** Can Cu */
            can_cu?: string[];
            /** Goi Y Thuong Luong */
            goi_y_thuong_luong?: string | null;
            /** Legal Basis */
            legal_basis?: components["schemas"]["LegalCitation"][];
            /** Evidence Status */
            evidence_status?: ("supported" | "insufficient_evidence" | "unsupported" | "legacy_unverified") | null;
        };
        /** Message */
        Message: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** PhanTichItem */
        PhanTichItem: {
            /**
             * Id
             * @default
             */
            id: string;
            /**
             * Dieu Khoan Noi Ve Ben
             * @default ben_b
             */
            dieu_khoan_noi_ve_ben: string;
            /**
             * Dieu Khoan Lam Gi
             * @default
             */
            dieu_khoan_lam_gi: string;
            /**
             * Ket Luan
             * @default PASS
             */
            ket_luan: string;
            /**
             * Giai Thich
             * @default
             */
            giai_thich: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /** Contract Type */
            contract_type?: string | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
            /** Retrieved Chunks */
            retrieved_chunks: {
                [key: string]: unknown;
            }[];
            /** Confidence */
            confidence: string;
            /** Status */
            status: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** StructuredContractResponse */
        StructuredContractResponse: {
            contract_info: components["schemas"]["ContractInfo"];
            party_a: components["schemas"]["ContractParty"];
            party_b: components["schemas"]["ContractParty"];
            /** Appendix Equipment */
            appendix_equipment: components["schemas"]["ContractEquipmentItem"][];
            /** Clauses */
            clauses?: components["schemas"]["ContractClause"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ocr_contract_api_ocr_contract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ocr_contract_api_ocr_contract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOCRResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ocr_contract_structured_api_ocr_contract_structured_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ocr_contract_structured_api_ocr_contract_structured_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStructuredOCRResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_file_rag_ingest_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestFileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_upload_rag_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_rag_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_sample_rag_ingest_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestFileResponse"];
                };
            };
        };
    };
    search_rag_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_rag_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_rag_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusResponse"];
                };
            };
        };
    };
    types_checklist_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistSummary"][];
                };
            };
        };
    };
    detail_checklist__loai_hop_dong__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loai_hop_dong: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_checklist_evaluate_clause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateClauseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateClauseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
